# TODO: schema for yaml, validation
# following jplusone properties are optional, if missin default values will be used

# com.grexdev.jplusone.core.properties.JPlusOneProperties
jplusone:
#  enabled: true
#  application-root-package: "com.grexdev.jplusone.test"
#  debug-mode: false
  report:
#    enabled: true
#    proxy-call-frames-hidden: false
    operation-filtering-mode: ALL_OPERATIONS
#    statement-filtering-mode: ALL_STATEMENTS
