package com.grexdev.nplusone.core.proxy.datasource;

import lombok.RequiredArgsConstructor;
import lombok.experimental.Delegate;
import lombok.extern.slf4j.Slf4j;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

@Slf4j
@RequiredArgsConstructor
public class ProxyConnection implements Connection {

    @Delegate(excludes = ConnectionOverwrite.class)
    private final Connection delegate;

    private final ProxyContext context;

    @Override
    public Statement createStatement() throws SQLException {
        if (context.isRecording()) {
            log.debug("===== createStatement 1 ===");
        }
        Statement statement = delegate.createStatement();
        return new ProxyStatement(statement, context);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        if (context.isRecording()) {
            log.debug("===== createStatement 2 ===");
        }
        Statement statement = delegate.createStatement(resultSetType, resultSetConcurrency);
        return new ProxyStatement(statement, context);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        if (context.isRecording()) {
            log.debug("===== createStatement 3 ===");
        }
        Statement statement = delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
        return new ProxyStatement(statement, context);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        if (context.isRecording()) {
            log.debug("===== prepareStatement 1 ===");
        }
        PreparedStatement preparedStatement = delegate.prepareStatement(sql);
        return new ProxyPreparedStatement(preparedStatement, context, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        if (context.isRecording()) {
            log.debug("===== prepareStatement 2 ===");
        }
        PreparedStatement preparedStatement = delegate.prepareStatement(sql, resultSetType, resultSetConcurrency);
        return new ProxyPreparedStatement(preparedStatement, context, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        if (context.isRecording()) {
            log.debug("===== prepareStatement 3 ===");
        }
        PreparedStatement preparedStatement = delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
        return new ProxyPreparedStatement(preparedStatement, context, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        if (context.isRecording()) {
            log.debug("===== prepareStatement 4 ===");
        }
        PreparedStatement preparedStatement = delegate.prepareStatement(sql, autoGeneratedKeys);
        return new ProxyPreparedStatement(preparedStatement, context, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        if (context.isRecording()) {
            log.debug("===== prepareStatement 5 ===");
        }
        PreparedStatement preparedStatement = delegate.prepareStatement(sql, columnIndexes);
        return new ProxyPreparedStatement(preparedStatement, context, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        if (context.isRecording()) {
            log.debug("===== prepareStatement 6 ===");
        }
        PreparedStatement preparedStatement = delegate.prepareStatement(sql, columnNames);
        return new ProxyPreparedStatement(preparedStatement, context, sql);
    }

    private interface ConnectionOverwrite {

        Statement createStatement() throws SQLException;

        Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException;

        Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;


        PreparedStatement prepareStatement(String sql) throws SQLException;

        PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;

        PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;

        PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;

        PreparedStatement prepareStatement(String sql, int columnIndexes[]) throws SQLException;

        PreparedStatement prepareStatement(String sql, String columnNames[]) throws SQLException;

    }

}
